#Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxMemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  pod 'SwiftLint'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxCoreData'

  # Pods for RxMemo

end
